# Generated by Django 3.2 on 2021-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='fullname',
            field=models.CharField(max_length=32),
        ),
    ]
