# Generated by Django 3.2 on 2021-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_alter_userregistration_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='fullname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='regdate',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='firstname',
            field=models.CharField(default='What is your name?', max_length=32),
        ),
    ]
